### PR TITLE
Allow server to free up resources (port)

### PR DESCRIPTION
**Pull request by hamnis**
Makes it possible to make it work better with other build tools than maven

### CODE REVIEW

**Comment by hamnis** [comment]
@googlebot I signed it!

**Comment by eamonnmcmanus** [comment]
Thanks for the PR! But the test failures seem legitimate?

**Comment by grant** [comment]
Hi @hamnis, do you want to look at the errors for this PR and continue with it, or can I close this PR?

**Review by grant — CHANGES_REQUESTED** [review]
Thanks again for the PR. Since there's been no activity for awhile and the test failure is legitimate, I'm going to request changes and close this PR. If there is more activity on this PR, I'm happy to re-open, just ping!

**Pull request closed without merging**
